on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/deploy-infra.yml'
    - '.tool-versions'
    - 'deployment/**'
  workflow_dispatch:  

jobs:
  build:
    name: plan
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v3
      - uses: asdf-vm/actions/plugins-add@v3
      - run: asdf install gcloud && asdf install terraform
      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'dunningnatural-3e6e829d'
          workload_identity_provider: 'projects/7571523860/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider'
      - run: |
          export CLOUDFLARE_API_TOKEN=$(./scripts/fetch_cloudflare_secret.sh)
          echo "::add-mask::$CLOUDFLARE_API_TOKEN"
          cd deployment
          terraform init
          terraform plan
