on:
  push:
    branches:
    - main
  workflow_dispatch:  

jobs:
  build:
    name: build static site
    runs-on: ubuntu-22.04
    steps:
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3
      - name: run build
        run: npm run build
