on:
  push:
    branches:
    - main
  workflow_dispatch:  

jobs:
  build:
    name: build static site
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3
      - name: npm install
        run: npm clean-install
      - name: run build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: site
          path: ./public
